#server:
#  servlet:
#    context-path: /api
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/buzzpressdb
    password: quicuxeo
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
